exclude: '.*'
repos:
  - repo: 'https://github.com/golangci/golangci-lint'
    rev: v1.45.2
    hooks:
      - id: golangci-lint
        entry: golangci-lint run -vvv
  - repo: 'https://github.com/zhenzou/pre-commit-golang'
    rev: master
    hooks:
      - id: go-fmt