name: 'Auto Assign Review'
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - testing/*
      - feature/*
      - refactor/*

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}