name: "Auto Assign Review"
on:
  pull_request:
    types: [opened, reopened]
     branches:
      - testing/*
      - feature/*
      - refactor/*
      - master
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: delivery-much/actions-assigner@v1
        with:
          reviewers: SMLsk